volumes:
  db-boostify:

services:
  postgres-db-boostify:
    image: postgres:14.13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: boostify
    ports:
      - 5432:5432
    volumes:
      - db-boostify:/var/lib/postgresql